stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-openjdk-8
          shellScript: mvn clean install -DskipTests
  - name: Build Docker
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: docker.dev.folio.org/mod-circulation:core-functional-latest
          pushRemote: true
          registry: docker.dev.folio.org
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-9mwdx:core-functional-helmcharts-mod-circulation
          version: 0.1.9
          answers:
            image.repository: docker.dev.folio.org/mod-circulation
            image.tag: core-functional-latest
          name: mod-circulation
          targetNamespace: core-functional
      - runScriptConfig:
          image: docker.io/iscompetent/update-module-descriptor
          shellScript: echo 'finish'
        env:
          APP_NAME: mod-circulation
        envFrom:
          - sourceName: tenant-config
            sourceKey: OKAPI_URL
            targetKey: OKAPI
timeout: 20
notification: {}
